global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']  # Change port if needed
#      - targets: ['192.168.1.167:8082']  # Change port if needed
